version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
      - ./mysqlconfig:/etc/mysql/conf.d


  web:
    build: .
    command: bash -c "bundle exec whenever --update-crontab && bundle exec rails s -d -p 3000 -b '0.0.0.0' && cron -f"
    volumes:
      - .:/Users/d-yamauchi/Documents/apps/rss-sharp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - "TZ=Japan"
